CREATE TABLE IF NOT EXISTS projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text, 
    deliverydate date NOT NULL
    

);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS INDETITY
    name text NOT NULL CHECK (name <> ''),
    done boolean,
    projectId integer REFERENCES projects(ID)

)




INSERT INTO projects(name, priority, description, deliverydate)
    values('Make a web App', 1, 'Using JavaScript' , 2019-05-12);


INSERT INTO projects(name, priority, description, deliverydate)
    values('Make an App', 1, 'Using Dart' , '2019-05-13');
    
INSERT INTO projects(name, priority, description, deliverydate)
    values('Make a Desktop App', 1, 'Using C++' , '2019-05-14');



-- INSERT TASKS DATA

INSERT INTO tasks (name, done, projectId)
    values('downlaod VueJs',false, 1);
    
INSERT INTO tasks (name, done, projectId)
    values('Create UI WEB ',false, 1);
    
INSERT INTO tasks (name, done, projectId)
    values('Downlaod Flutter',false, 2);
    
INSERT INTO tasks (name, done, projectId)
    values('Design UI',false, 2);
    
INSERT INTO tasks (name, done, projectId)
    values('downlaod VueJs',false, 1);

